# Generated by Django 5.2.5 on 2025-09-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_est', models.TextField()),
                ('apellido_paterno_est', models.TextField()),
                ('apellido_materno_est', models.TextField()),
                ('email_est', models.EmailField(max_length=254, unique=True)),
                ('nota_est', models.FloatField()),
            ],
        ),
    ]
