# Generated by Django 5.2.5 on 2025-09-02 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_est', models.CharField(max_length=100)),
                ('apellido_paterno_est', models.CharField(max_length=100)),
                ('apellido_materno_est', models.CharField(max_length=100)),
                ('email_est', models.EmailField(max_length=254, unique=True)),
                ('nota_est', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
            ],
        ),
    ]
